"""Prompts used by the active AssessNex AI generation pipeline."""

from .base import SYSTEM_PROMPT, FEW_SHOT_EXAMPLES
from .standard import (
    TRUE_FALSE_PROMPT, FILL_IN_BLANK_PROMPT, CODING_PROMPT, SCENARIO_PROMPT,
    COMPLEXITY_PROMPT, CODE_OUTPUT_PROMPT, QUESTION_TYPE_PROMPTS,
)
from .plagiarism import PLAGIARISM_CHECK_PROMPT

__all__ = [
    "SYSTEM_PROMPT", "FEW_SHOT_EXAMPLES",
    "TRUE_FALSE_PROMPT", "FILL_IN_BLANK_PROMPT", "CODING_PROMPT",
    "SCENARIO_PROMPT", "COMPLEXITY_PROMPT", "CODE_OUTPUT_PROMPT",
    "QUESTION_TYPE_PROMPTS", "PLAGIARISM_CHECK_PROMPT",
]
