"""Advanced prompts package"""

from .paper_generation_prompts import (
    QUESTION_PAPER_GENERATION,
    BALANCED_PAPER_TEMPLATE,
    PAPER_ARRANGEMENT_STRATEGIES,
    ANSWER_KEY_GENERATION,
    PLAGIARISM_CHECK_PROMPT,
    PAPER_GENERATION_TYPES,
    ADVANCED_TYPES,
)

__all__ = [
    'QUESTION_PAPER_GENERATION',
    'BALANCED_PAPER_TEMPLATE',
    'PAPER_ARRANGEMENT_STRATEGIES',
    'ANSWER_KEY_GENERATION',
    'PLAGIARISM_CHECK_PROMPT',
    'PAPER_GENERATION_TYPES',
    'ADVANCED_TYPES',
]
