"""Specialized prompts package"""

from .coding_prompts import (
    CODING_BASIC_PROMPT,
    CODING_INTERMEDIATE_PROMPT,
    CODING_ADVANCED_PROMPT,
    CODING_WITH_TESTS_PROMPT,
    CODING_TYPE_PROMPTS,
)

from .image_prompts import (
    IMAGE_BASED_PROMPT,
    ALGORITHM_FLOW_PROMPT,
    ANT_COLONY_VISUALIZATION,
    GRAPH_ALGORITHM_VISUALIZATION,
    IMAGE_QUESTION_TYPES,
)

from .assignment_prompts import (
    ASSIGNMENT_BASIC_PROMPT,
    ASSIGNMENT_INTERMEDIATE_PROMPT,
    ASSIGNMENT_ADVANCED_PROMPT,
    PROJECT_SETUP_TEMPLATE,
    ASSIGNMENT_TYPES,
)

__all__ = [
    # Coding
    'CODING_BASIC_PROMPT',
    'CODING_INTERMEDIATE_PROMPT',
    'CODING_ADVANCED_PROMPT',
    'CODING_WITH_TESTS_PROMPT',
    'CODING_TYPE_PROMPTS',
    # Image
    'IMAGE_BASED_PROMPT',
    'ALGORITHM_FLOW_PROMPT',
    'ANT_COLONY_VISUALIZATION',
    'GRAPH_ALGORITHM_VISUALIZATION',
    'IMAGE_QUESTION_TYPES',
    # Assignment
    'ASSIGNMENT_BASIC_PROMPT',
    'ASSIGNMENT_INTERMEDIATE_PROMPT',
    'ASSIGNMENT_ADVANCED_PROMPT',
    'PROJECT_SETUP_TEMPLATE',
    'ASSIGNMENT_TYPES',
]
